version: '3.7'


services:

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
      - data_get
    ports:
      - 0.0.0.0:1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  adaptor:
    image: dorogans/iot-hub
    hostname: adaptor
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - data_get
      - data_save
    environment:
      - DEBUG_DATA_FLOW=${DEBUG_DATA_FLOW:-false}
    volumes:
      - ./adaptor/adaptor.py:/app/adaptor.py

  influxdb:
    image: influxdb
    hostname: influxdb
    networks:
      - data_save
      - data_show
    volumes:
      - influxdb_vol:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    hostname: grafana
    depends_on:
      - influxdb
    networks:
      - data_show
    ports:
      - 0.0.0.0:80:3000
    volumes:
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
      - ./grafana/storage/grafana:/var/lib/grafana:rw


volumes:
  influxdb_vol:

networks:
  data_get:
  data_save:
  data_show: